name: create-release
run-name: Create new release
on:
  push:
    tags:
      - v*
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GO environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.4
          check-latest: false

      - name: Build release assets
        run: RELEASE_TAG=${{ github.ref_name }} make release

      - name: Create release on GitHub
        run: gh release create ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets to GitHub
        run: gh release upload ${{ github.ref_name }} ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
