name: create-release
run-name: Create new release
on:
  push:
    tags:
      - v*
jobs:
  build-assets:
    name: Build assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup GO environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.4
          check-latest: false
      - run: make release
      - run: gh release create ${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN : ${{ github.token }}
      - run: gh release upload ${{ github.ref_name }} ./assets/*